version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DATABASE=axis_db
      - JWT_SECRET=your_jwt_secret
      - JWT_EXPIRATION=24h
    depends_on:
      - mongodb
    networks:
      - axis-network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - axis-network
    restart: unless-stopped

networks:
  axis-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local