openapi: 3.0.0
info:
  title: Axis Backend Assessment API
  description: API documentation for the Axis Backend Assessment
  version: 1.0.0

servers:
  - url: http://localhost:8000
    description: Local development server

paths:
  /api/v1/transactions/deposit:
    post:
      tags:
        - transactions
      summary: Deposit money into account
      description: Deposit money into a user's account and create a transaction record
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionRequest'
      responses:
        '200':
          description: Successful deposit
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
        '400':
          description: Bad request - Invalid input or insufficient balance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - Invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/balances/{account_id}:
    get:
      tags:
        - balances
      summary: Get account balances
      description: Get all currency balances for a specific account
      security:
        - BearerAuth: []
      parameters:
        - name: account_id
          in: path
          required: true
          description: ID of the account to get balances for
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResponse'
        '400':
          description: Bad request - Invalid account ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - Invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/transactions/withdraw:
    post:
      tags:
        - transactions
      summary: Withdraw money from account
      description: Withdraw money from a user's account and create a transaction record
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionRequest'
      responses:
        '200':
          description: Successful withdrawal
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
        '400':
          description: Bad request - Invalid input or insufficient balance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - Invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/auth/register:
    post:
      tags:
        - Authentication
      summary: Register a new user
      description: Creates a new user account with the provided information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: User successfully registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Bad request - validation errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Conflict - email already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/auth/login:
    post:
      tags:
        - Authentication
      summary: Login user
      description: Authenticates a user and returns a JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Bad request - validation errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    TransactionRequest:
      type: object
      required:
        - account_id
        - amount
        - currency
      properties:
        account_id:
          type: string
          description: The ID of the account to perform the transaction on
          example: "507f1f77bcf86cd799439011"
        amount:
          type: number
          format: float
          description: The amount to deposit or withdraw
          minimum: 0.01
          example: 100.50
        currency:
          type: string
          description: The currency code (ISO 4217)
          minLength: 3
          maxLength: 3
          example: "USD"

    BalanceResponse:
      type: object
      properties:
        account_id:
          type: string
          description: The ID of the account
          example: "507f1f77bcf86cd799439011"
        balances:
          type: array
          items:
            $ref: '#/components/schemas/CurrencyBalance'

    CurrencyBalance:
      type: object
      properties:
        currency:
          type: string
          description: The currency code (ISO 4217)
          example: "USD"
        amount:
          type: number
          format: float
          description: The current balance amount
          example: 1000.50

    TransactionResponse:
      type: object
      properties:
        transaction_id:
          type: string
          description: The ID of the created transaction
          example: "507f1f77bcf86cd799439011"

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error message
          example: "insufficient balance"

    # Authentication Schemas
    RegisterRequest:
      type: object
      required:
        - name
        - email
        - phone_number
        - password
      properties:
        name:
          type: string
          minLength: 2
          maxLength: 100
          example: "John Doe"
        email:
          type: string
          format: email
          example: "john.doe@example.com"
        phone_number:
          type: string
          pattern: "^\\+[1-9]\\d{1,14}$"
          example: "+12125551234"
        password:
          type: string
          format: password
          minLength: 8
          maxLength: 72
          example: "strongPassword123"

    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: "john.doe@example.com"
        password:
          type: string
          format: password
          minLength: 8
          maxLength: 72
          example: "strongPassword123"

    AuthResponse:
      type: object
      properties:
        token:
          type: string
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        user:
          $ref: '#/components/schemas/Account'

    Account:
      type: object
      properties:
        id:
          type: string
          example: "507f1f77bcf86cd799439011"
        name:
          type: string
          example: "John Doe"
        email:
          type: string
          format: email
          example: "john.doe@example.com"
        phone_number:
          type: string
          example: "+12125551234"
        status:
          type: string
          example: "active"
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Invalid credentials"
        errors:
          type: object
          additionalProperties:
            type: string
          example:
            email: "Invalid email format"
            password: "Password must be at least 8 characters"
